# Project: 项目管理2026
# Makefile created by Red Panda C++ 3.3.3147

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
WINDRESFLAGS = 
RES      = 项目管理2026_private.res
OBJ      = ScoreWork.o main.o StudentWork.o StudentController.o ScoreController.o CourseController.o CourseWork.o $(RES)
BIN      = 项目管理2026.exe
LINKOBJ  = "ScoreWork.o" "main.o" "StudentWork.o" "StudentController.o" "ScoreController.o" "CourseController.o" "CourseWork.o" "项目管理2026_private.res"
CLEANOBJ = "ScoreWork.o" "main.o" "StudentWork.o" "StudentController.o" "ScoreController.o" "CourseController.o" "CourseWork.o" "项目管理2026_private.res" "项目管理2026.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

项目管理2026.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "项目管理2026.exe" $(LIBS)

ScoreWork.o: ScoreWork.cpp DataType.h CourseWork.h ScoreWork.h StudentWork.h
	$(CXX) -c "ScoreWork.cpp" -o "ScoreWork.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

main.o: main.cpp StudentController.h DataType.h CourseWork.h CourseController.h ScoreController.h
	$(CXX) -c "main.cpp" -o "main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

StudentWork.o: StudentWork.cpp DataType.h StudentWork.h
	$(CXX) -c "StudentWork.cpp" -o "StudentWork.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

StudentController.o: StudentController.cpp DataType.h StudentWork.h
	$(CXX) -c "StudentController.cpp" -o "StudentController.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

ScoreController.o: ScoreController.cpp DataType.h CourseWork.h ScoreWork.h
	$(CXX) -c "ScoreController.cpp" -o "ScoreController.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

CourseController.o: CourseController.cpp DataType.h CourseWork.h
	$(CXX) -c "CourseController.cpp" -o "CourseController.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

CourseWork.o: CourseWork.cpp DataType.h CourseWork.h
	$(CXX) -c "CourseWork.cpp" -o "CourseWork.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

项目管理2026_private.res: 项目管理2026_private.rc 
	$(WINDRES) -i "项目管理2026_private.rc" --input-format=rc -o "项目管理2026_private.res" -O coff $(WINDRESFLAGS) 

